### ISSUE TITLE
Null result returns error

### ISSUE THREAD

**Issue by hover2pi** [dr-rodriguez/AstrodbWeb#1]
If the query returns nothing but the SQL was legit, it should maybe return '0 records found' or something rather than an error.

**Comment by dr-rodriguez** [comment]
Technically it does, but the problem is that a mistyped query returns the same result (ie, null) as a good query with no objects. Perhaps the best way is to change astrodbkit so that if the query is mistyped it raises an AttributeError rather than print out 'could not execute query'. We could then catch this error and treat it separately from a null result.

**Comment by dr-rodriguez** [comment]
Updated error handling to treat incorrect SQL queries differently from null results by grabbing the printed output error message.
